import type { InvestigatedInterval } from "@bedrock-engineer/bro-xml-parser";
import * as Plot from "@observablehq/plot";
import {
  createWatermarkMark,
  depthYAxisConfig,
  type TranslateFunction,
} from "../../util/plot-config";

export interface DeterminationConfig {
  key: string;
  getValue: (d: InvestigatedInterval) => number | null | undefined;
  domain: [number, number];
  label: string;
  unit: string;
  ticks: number;
}

/** An interval that can be placed on the depth axis: both depths present. */
type PlottableInterval = InvestigatedInterval & {
  beginDepth: number;
  endDepth: number;
};

const FIRST_COL_WIDTH = 200;
const OTHER_COL_WIDTH = 160;
const FIRST_MARGIN_LEFT = 50;
const OTHER_MARGIN_LEFT = 10;
const MARGIN_RIGHT = 5;
const PLOT_HEIGHT = 400;

interface BuildDepthProfilesOptions {
  intervals: Array<InvestigatedInterval>;
  determinations: Array<DeterminationConfig>;
  maxDepth: number;
  t: TranslateFunction;
}

/**
 * Build a combined depth-profile figure: one narrow Plot column per available
 * determination, sharing a single depth axis, nested into one parent SVG.
 * Returns null when there are no determinations to plot.
 */
export function buildDepthProfilesPlot({
  intervals,
  determinations,
  maxDepth,
  t,
}: BuildDepthProfilesOptions): (SVGSVGElement | HTMLElement) | null {
  if (determinations.length === 0) {
    return null;
  }

  const count = determinations.length;
  const totalWidth = FIRST_COL_WIDTH + (count - 1) * OTHER_COL_WIDTH;

  // Create parent SVG to hold the per-determination columns
  const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  svg.setAttribute("width", String(totalWidth));
  svg.setAttribute("height", String(PLOT_HEIGHT));
  svg.setAttribute("viewBox", `0 0 ${totalWidth} ${PLOT_HEIGHT}`);
  svg.style.backgroundColor = "white";
  // Allow tooltips from the outer columns to paint past the parent viewport too.
  svg.style.overflow = "visible";

  let xOffset = 0;

  for (const [index, det] of determinations.entries()) {
    const isFirst = index === 0;
    const colWidth = isFirst ? FIRST_COL_WIDTH : OTHER_COL_WIDTH;

    const dataPoints = intervals.filter(
      (interval): interval is PlottableInterval =>
        det.getValue(interval) != null &&
        interval.beginDepth != null &&
        interval.endDepth != null,
    );

    if (dataPoints.length === 0) {
      xOffset += colWidth;
      continue;
    }

    // Auto-extend domain if any data exceeds configured max
    const maxValue = Math.max(...dataPoints.map((d) => det.getValue(d) ?? 0));
    const xDomain: [number, number] =
      maxValue > det.domain[1] ? [det.domain[0], maxValue * 1.1] : det.domain;

    const childPlot = Plot.plot({
      width: colWidth,
      height: PLOT_HEIGHT,
      style: { backgroundColor: "transparent" },
      marginLeft: isFirst ? FIRST_MARGIN_LEFT : OTHER_MARGIN_LEFT,
      marginRight: MARGIN_RIGHT,
      marginTop: 30,
      marginBottom: 50,
      x: {
        domain: xDomain,
        label: `${det.label} (${det.unit})`,
        grid: true,
        ticks: det.ticks,
      },
      y: {
        ...depthYAxisConfig,
        domain: [0, maxDepth],
        ...(isFirst ? {} : { axis: null }),
      },
      marks: [
        Plot.frame(),
        Plot.dot(dataPoints, {
          x: det.getValue,
          y: (d: PlottableInterval) => (d.endDepth + d.beginDepth) / 2,
          symbol: "times",
          stroke: "#2563eb",
          strokeWidth: 2,
          title: (d: PlottableInterval) => {
            const value = det.getValue(d);
            return `${d.beginDepth.toFixed(2)} – ${d.endDepth.toFixed(2)} m\n${det.label}: ${value?.toFixed(2)} ${det.unit}`;
          },
          tip: true,
        }),
        createWatermarkMark(t("madeWithBedrockBroViewer"), { dy: 30 }),
      ],
    });

    // Nest the inner SVG generated by Plot into the parent
    const childSvg = childPlot as SVGSVGElement;
    childSvg.setAttribute("x", String(xOffset));
    childSvg.setAttribute("y", "0");
    childSvg.removeAttribute("viewBox");
    // Nested <svg> viewports clip their overflow by default (UA stylesheet
    // `svg:not(:root) { overflow: hidden }`), which cuts off any tooltip wider
    // than this narrow column. Let the tip paint past the column edge instead.
    childSvg.style.overflow = "visible";
    // Later columns paint on top, so a hovered column's tip would be covered by
    // its right-hand neighbours. Raise the column to the end of the paint order
    // while it's hovered so its tip stays on top.
    childSvg.addEventListener("pointerenter", () => {
      svg.append(childSvg);
    });
    svg.append(childSvg);

    xOffset += colWidth;
  }

  return svg;
}
